import Head from 'next/head'
import styled from 'styled-components'
import Image from 'next/image'
import Header from '../components/header/header'

const Title = styled.h2`
  margin: 0;
  padding: 0;
  font-size: 64px;
  line-height: 88px;
  font-weight: 700;
  justify-content: space-between;
  font-style: normal;
  letter-spacing: 1px;
  color: #262338;
`

const Container = styled.main`
  width: 588px;
  padding: 92px 113px;
`

const Subtitle = styled.p`
  width: 564px;
  margin: 20px 0 28px 0;
  font-size: 20px;
  font-style: normal;
  font-weight: 400;
  line-height: 32px;
  letter-spacing: 0.75px;
  text-align: left;
  color: #4E4B66;
`

const Economy = styled.p`
  display: flex;
  align-items: center;
`

const Span = styled.span`
  font-size: 15px;
  line-height: 24px;
  letter-spacing: 0.75px;
  color: #4E4B66;
`

const Info = styled.span`
  width: 564px;
  margin: 20px 0 28px 0;
  font-size: 18px;
  font-style: normal;
  font-weight: 600;
  line-height: 32px;
  letter-spacing: 0.75px;
  text-align: left;
  color: #262338;
`

export default function Home() {
  return (
    <div>
      <Head>
        <title>ClimAct</title>
        <meta name="description" content="Generated by create next app"/>
      </Head>
      <Header/>
      <Container>
        <Title>
          Act now for change
        </Title>
        <Subtitle>
          A subititle for your landing page describing your product or service that you provide.
        </Subtitle>
        <div>
          <Info>Saved :</Info>
          <div>
            <Image
              src="/icons/svg/BlackLightning.svg"
              alt="light"
              width={21}
              height={29}
            />
          </div>
          <Span>3000kw</Span>
          <div>
            <Image
              src="/icons/svg/Drop.svg"
              alt="drop"
              width={21}
              height={29}
            />
          </div>
          <Span>20000l</Span>
        </div>
      </Container>
    </div>
  )
}
